security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'

    providers:
        default_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: default_provider
            lazy: true
            form_login:
                login_path: user-login
                check_path: user-login
                enable_csrf: true
            logout:
                path: user-logout
            access_denied_handler: App\Security\AccessDeniedHandler
            user_checker: App\Security\UserChecker

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    access_control:
    # User authentication required
        - { path: ^/user/$, roles: ROLE_USER }
        - { path: ^/logout, roles: ROLE_USER }
    # admin area
        - { path: ^/administrator, roles: ROLE_ADMIN }
        - { path: ^/user/(general|password|roles)/\d+$, roles: ROLE_ADMIN }
        - { path: ^/user/roles$, roles: ROLE_ADMIN }