parameters:
    supported_locales:
        - en
        - ua

framework:
    default_locale: en
    enabled_locales: '%supported_locales%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en