twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/custom_types.html.twig'
    globals:
        app_locales: '%app_locales%'
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'