version: '3.2'
services:
  db:
    image: bitnami/mariadb:10.6.17
    volumes:
      - mariadb_data:/bitnami/mariadb
    ports:
      - "3306:${MYSQL_PORT}"
    environment:
      - "MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MARIADB_DATABASE=${MYSQL_DATABASE}"
      - "MARIADB_USER=${MYSQL_USER}"
      - "MARIADB_PASSWORD=${MYSQL_PASSWORD}"
    networks:
      - net

  test-db:
    image: bitnami/mariadb:10.6.17
    volumes:
      - test_DB:/bitnami/mariadb
    ports:
      - "3307:${MYSQL_PORT}"
    environment:
      - "MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MARIADB_DATABASE=${MYSQL_DATABASE}"
      - "MARIADB_USER=${MYSQL_USER}"
      - "MARIADB_PASSWORD=${MYSQL_PASSWORD}"
    networks:
      - net

  fpm:
    build: docker/php
    volumes:
      - './:/var/www/html'
      - './docker/php/php.ini:/opt/bitnami/php/etc/php.ini'
      - './docker/php/xdebug.ini:/opt/bitnami/php/etc/conf.d/xdebug.ini'
    ports:
      - '9000:9000'
    working_dir: '/var/www/html'
    command: 'php-fpm -F'
    networks:
      - net

  httpd:
    image: 'httpd:2.4'
    depends_on:
      - 'fpm'
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html:ro'
      - './docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/httpd/host.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - net

  mailhog:
    image: mailhog/mailhog:latest
    hostname: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  mariadb_data:
    driver: "local"
  test_DB:
    driver: "local"
