article-list:
  path: /administrator/articles
  controller: App\Controller\ArticleController::index

article-create:
  path: /administrator/article
  controller: App\Controller\ArticleController::create

article-edit:
  path: /administrator/article/{slug}/{locale}
  controller: App\Controller\ArticleController::update
  requirements:
    slug: '^[\w\-]+$'

article-translate:
  path: /administrator/article/translate/{id}/{locale}
  controller: App\Controller\ArticleController::translate
  requirements:
    id: '^\d+$'
    locale: 'en|ua'

article-delete:
  path: /administrator/article/delete
  methods: [POST]
  controller: App\Controller\ArticleController::delete
