images-list:
  controller: App\Controller\ImageController::index
  path: administrator/images

images-upload:
  controller: App\Controller\ImageController::upload
  path: administrator/images/upload
