name: Quality check

on:
  push:
    branches:
      - main

jobs:
  create-basic-system:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Copy default config
        run: cp .env.dist .env

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Composer install
        run: docker-compose -f "docker-compose.yml" exec -T fpm composer install

      - name: Yarn install
        run: docker-compose -f "docker-compose.yml" exec -T fpm yarn install

      - name: Build front end
        run: docker-compose -f "docker-compose.yml" exec -T fpm yarn encore dev

      - name: Add empty tables to the DB
        run: docker-compose -f "docker-compose.yml" exec -T fpm php bin/console doctrine:migrations:migrate

      - name: Run PHP-CS-fixer
        run: docker-compose -f "docker-compose.yml" exec -T fpm composer csfixer

      - name: Run PHP-CS-fixer
        run: docker-compose -f "docker-compose.yml" exec -T fpm composer psalm

      - name: Run PHP-CS-fixer
        run: docker-compose -f "docker-compose.yml" exec -T fpm composer phpStan

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down